// Dados simulados para a plataforma

export const mockUser = {
  id: '1',
  name: 'Dr. Maria Silva',
  email: 'maria.silva@email.com',
  avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
  plan: 'Profissional',
  createdAt: '2024-01-15',
};

export const mockPlatforms = [
  {
    id: '1',
    name: 'Clínica Mente Sã',
    type: 'clinica-psicologica',
    status: 'active',
    url: 'https://clinicamentesa.com.br',
    createdAt: '2024-03-15',
    monthlyVisits: 1250,
    totalPatients: 45,
    monthlyRevenue: 12500,
    aiInteractions: 340,
    description: 'Clínica especializada em terapia cognitivo-comportamental e atendimento psicológico.',
  },
];

export const mockAnalytics = {
  totalVisits: 1250,
  totalPatients: 45,
  totalRevenue: 12500,
  aiInteractions: 340,
  conversionRate: 15.6,
  averageSessionTime: '4m 32s',
  bounceRate: 32.4,
  monthlyGrowth: {
    visits: 18.2,
    patients: 12.5,
    revenue: 22.1,
    interactions: 45.3,
  },
  sessionsThisMonth: 180,
  averageSessionsPerPatient: 4.2,
  recurringPatients: 38,
  chartData: {
    visits: [
      { month: 'Jan', visits: 856, patients: 28 },
      { month: 'Fev', visits: 982, patients: 35 },
      { month: 'Mar', visits: 1250, patients: 45 },
      { month: 'Abr', visits: 1180, patients: 42 },
      { month: 'Mai', visits: 1350, patients: 48 },
      { month: 'Jun', visits: 1420, patients: 52 },
    ],
    revenue: [
      { month: 'Jan', revenue: 8400 },
      { month: 'Fev', revenue: 10500 },
      { month: 'Mar', revenue: 12500 },
      { month: 'Abr', revenue: 11800 },
      { month: 'Mai', revenue: 13200 },
      { month: 'Jun', revenue: 14600 },
    ],
    attendance: [
      { month: 'Jan', rate: 85 },
      { month: 'Fev', rate: 88 },
      { month: 'Mar', rate: 92 },
      { month: 'Abr', rate: 87 },
      { month: 'Mai', rate: 90 },
      { month: 'Jun', rate: 94 },
    ],
  },
};

export const mockAppointments = [
  {
    id: '1',
    patientName: 'Ana Costa',
    date: '2024-12-26',
    time: '09:00',
    type: 'Terapia Individual',
    status: 'confirmed',
    duration: 50,
    notes: 'Primeira consulta - ansiedade generalizada',
    paymentStatus: 'paid',
    isRecurring: true,
    sessionNumber: 8,
  },
  {
    id: '2',
    patientName: 'João Santos',
    date: '2024-12-26',
    time: '10:30',
    type: 'Terapia de Casal',
    status: 'confirmed',
    duration: 60,
    notes: 'Sessão de continuidade - questões de comunicação',
    paymentStatus: 'pending',
    isRecurring: true,
    sessionNumber: 12,
  },
  {
    id: '3',
    patientName: 'Carla Oliveira',
    date: '2024-12-26',
    time: '14:00',
    type: 'Avaliação Psicológica',
    status: 'pending',
    duration: 90,
    notes: 'Avaliação neuropsicológica solicitada',
    paymentStatus: 'pending',
    isRecurring: false,
    sessionNumber: 1,
  },
  {
    id: '4',
    patientName: 'Pedro Lima',
    date: '2024-12-27',
    time: '09:30',
    type: 'Terapia Individual',
    status: 'confirmed',
    duration: 50,
    notes: 'Sessão semanal - transtorno do pânico',
    paymentStatus: 'paid',
    isRecurring: true,
    sessionNumber: 15,
  },
  {
    id: '5',
    patientName: 'Mariana Silva',
    date: '2024-12-27',
    time: '11:00',
    type: 'Terapia Individual',
    status: 'confirmed',
    duration: 50,
    notes: 'Trabalhando questões de autoestima',
    paymentStatus: 'paid',
    isRecurring: true,
    sessionNumber: 6,
  },
  {
    id: '6',
    patientName: 'Roberto Mendes',
    date: '2024-12-28',
    time: '08:30',
    type: 'Avaliação Psicológica',
    status: 'pending',
    duration: 120,
    notes: 'Avaliação para concurso público',
    paymentStatus: 'pending',
    isRecurring: false,
    sessionNumber: 1,
  },
];

export const mockPatients = [
  {
    id: '1',
    name: 'Ana Costa',
    email: 'ana.costa@email.com',
    phone: '(11) 98765-4321',
    birthDate: '1985-03-15',
    registeredAt: '2024-01-10',
    lastSession: '2024-12-20',
    totalSessions: 8,
    status: 'active',
    diagnosis: 'Transtorno de Ansiedade Generalizada',
    notes: 'Paciente apresenta boa evolução no tratamento com TCC. Utilizando técnicas de respiração e reestruturação cognitiva.',
    insurance: 'Unimed',
    emergencyContact: 'Carlos Costa (marido) - (11) 99999-1111',
    sessionFrequency: 'weekly',
    therapyGoals: ['Reduzir sintomas de ansiedade', 'Melhorar qualidade do sono', 'Desenvolver estratégias de enfrentamento'],
    medicalHistory: 'Histórico de ansiedade na família. Primeira crise aos 20 anos.',
    currentMedication: 'Sertralina 50mg',
  },
  {
    id: '2',
    name: 'João Santos',
    email: 'joao.santos@email.com',
    phone: '(11) 97654-3210',
    birthDate: '1978-07-22',
    registeredAt: '2024-02-05',
    lastSession: '2024-12-19',
    totalSessions: 12,
    status: 'active',
    diagnosis: 'Terapia de Casal',
    notes: 'Casal em processo de melhoria da comunicação. Trabalhando questões de confiança e intimidade.',
    insurance: 'SulAmérica',
    emergencyContact: 'Maria Santos (esposa) - (11) 98888-2222',
    sessionFrequency: 'bi-weekly',
    therapyGoals: ['Melhorar comunicação conjugal', 'Resolver conflitos de forma saudável', 'Fortalecer intimidade'],
    medicalHistory: 'Sem histórico psiquiátrico anterior.',
    currentMedication: 'Nenhum',
  },
  {
    id: '3',
    name: 'Carla Oliveira',
    email: 'carla.oliveira@email.com',
    phone: '(11) 96543-2109',
    birthDate: '1992-11-08',
    registeredAt: '2024-03-01',
    lastSession: '2024-12-18',
    totalSessions: 6,
    status: 'active',
    diagnosis: 'Episódio Depressivo Moderado',
    notes: 'Resposta positiva ao tratamento medicamentoso e psicoterapia. Melhora significativa do humor.',
    insurance: 'Particular',
    emergencyContact: 'Ana Oliveira (mãe) - (11) 97777-3333',
    sessionFrequency: 'weekly',
    therapyGoals: ['Estabilizar humor', 'Retomar atividades prazerosas', 'Fortalecer rede de apoio'],
    medicalHistory: 'Primeiro episódio depressivo. Histórico de depressão materna.',
    currentMedication: 'Fluoxetina 20mg',
  },
  {
    id: '4',
    name: 'Pedro Lima',
    email: 'pedro.lima@email.com',
    phone: '(11) 95432-1098',
    birthDate: '1990-05-12',
    registeredAt: '2024-09-15',
    lastSession: '2024-12-25',
    totalSessions: 15,
    status: 'active',
    diagnosis: 'Transtorno do Pânico',
    notes: 'Significativa redução na frequência e intensidade das crises. Paciente mais confiante.',
    insurance: 'Bradesco Saúde',
    emergencyContact: 'Laura Lima (esposa) - (11) 96666-4444',
    sessionFrequency: 'weekly',
    therapyGoals: ['Eliminar crises de pânico', 'Reduzir comportamentos de evitação', 'Retomar atividades sociais'],
    medicalHistory: 'Primeiras crises há 2 anos após estresse no trabalho.',
    currentMedication: 'Clonazepam 0.5mg (uso eventual)',
  },
  {
    id: '5',
    name: 'Mariana Silva',
    email: 'mariana.silva@email.com',
    phone: '(11) 94321-0987',
    birthDate: '1995-09-03',
    registeredAt: '2024-10-20',
    lastSession: '2024-12-24',
    totalSessions: 6,
    status: 'active',
    diagnosis: 'Baixa Autoestima e Ansiedade Social',
    notes: 'Trabalhando questões de autoestima e habilidades sociais. Progresso gradual mas consistente.',
    insurance: 'Particular',
    emergencyContact: 'Roberto Silva (pai) - (11) 95555-5555',
    sessionFrequency: 'weekly',
    therapyGoals: ['Melhorar autoestima', 'Desenvolver habilidades sociais', 'Reduzir ansiedade social'],
    medicalHistory: 'Timidez excessiva desde a infância. Bullying na adolescência.',
    currentMedication: 'Nenhum',
  },
];

export const mockChatMessages = [
  {
    id: '1',
    type: 'user',
    message: 'Oi, gostaria de agendar uma consulta',
    timestamp: '2024-12-25 14:30',
    patientName: 'Marina Silva',
    phone: '(11) 99887-6655',
  },
  {
    id: '2',
    type: 'ai',
    message: 'Olá Marina! Fico feliz em ajudar você a agendar sua consulta. Temos horários disponíveis para esta semana e a próxima. Você gostaria de uma consulta inicial ou já é nossa paciente?',
    timestamp: '2024-12-25 14:30',
  },
  {
    id: '3',
    type: 'user',
    message: 'É minha primeira vez, preciso de uma consulta inicial',
    timestamp: '2024-12-25 14:32',
    patientName: 'Marina Silva',
    phone: '(11) 99887-6655',
  },
  {
    id: '4',
    type: 'ai',
    message: 'Perfeito! Para primeira consulta reservamos 60 minutos. Temos as seguintes opções:\n\n📅 **Quinta-feira (26/12)**: 16:00h\n📅 **Sexta-feira (27/12)**: 10:30h ou 15:00h\n📅 **Segunda-feira (30/12)**: 09:00h ou 14:30h\n\nQual horário fica melhor para você?',
    timestamp: '2024-12-25 14:32',
  },
  {
    id: '5',
    type: 'user',
    message: 'Sexta-feira às 15:00h seria ideal!',
    timestamp: '2024-12-25 14:35',
    patientName: 'Marina Silva',
    phone: '(11) 99887-6655',
  },
];

export const mockQuestionnaireData = {
  businessType: 'clinica-psicologica',
  businessName: 'Clínica Mente Sã',
  ownerName: 'Dra. Maria Silva',
  crp: 'CRP 06/123456',
  specialties: ['Terapia Cognitivo-Comportamental', 'Ansiedade', 'Depressão'],
  sessionTypes: ['Consulta Individual', 'Terapia de Casal', 'Avaliação Psicológica'],
  workingHours: {
    monday: '08:00-18:00',
    tuesday: '08:00-18:00',
    wednesday: '08:00-18:00',
    thursday: '08:00-18:00',
    friday: '08:00-17:00',
  },
  sessionDuration: {
    individual: 50,
    couple: 60,
    evaluation: 90,
  },
  pricing: {
    individual: 120,
    couple: 180,
    evaluation: 250,
  },
  insurances: ['Unimed', 'Bradesco Saúde', 'SulAmérica'],
  communicationPreference: 'WhatsApp',
  emergencyContact: '(11) 99999-9999',
};