import type { Question } from '@/hooks/useQuestionnaires';

export interface QuestionnaireTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  estimatedTime: number;
  questions: Omit<Question, 'id'>[];
}

export const QUESTIONNAIRE_TEMPLATES: QuestionnaireTemplate[] = [
  {
    id: 'anamnese-completa',
    name: 'Anamnese Nutricional Completa',
    category: 'anamnese',
    description: 'Template completo de anamnese nutricional com todas as seções necessárias',
    estimatedTime: 30,
    questions: [
      // Caso Clínico
      {
        question_text: 'Qual o motivo principal da consulta?',
        question_type: 'text',
        section: 'Caso Clínico',
        is_required: true,
        order_index: 0,
      },
      {
        question_text: 'Observações gerais e histórico clínico',
        question_type: 'text',
        section: 'Caso Clínico',
        is_required: false,
        order_index: 1,
      },
      {
        question_text: 'Quais são seus objetivos principais?',
        question_type: 'multiple_choice',
        section: 'Caso Clínico',
        options: [
          'Perda de peso',
          'Ganho de massa muscular',
          'Melhorar saúde geral',
          'Melhorar performance',
          'Reeducação alimentar',
          'Outro',
        ],
        is_required: true,
        order_index: 2,
      },

      // Hábitos de Vida
      {
        question_text: 'Qual sua rotina de trabalho?',
        question_type: 'single_choice',
        section: 'Hábitos de Vida',
        options: [
          'Sedentário (escritório)',
          'Moderadamente ativo',
          'Muito ativo (trabalho físico)',
        ],
        is_required: true,
        order_index: 3,
      },
      {
        question_text: 'Quantas horas você dorme por noite?',
        question_type: 'single_choice',
        section: 'Hábitos de Vida',
        options: [
          'Menos de 5 horas',
          '5-6 horas',
          '7-8 horas',
          'Mais de 8 horas',
        ],
        is_required: true,
        order_index: 4,
      },
      {
        question_text: 'Qual seu nível de estresse no dia a dia?',
        question_type: 'scale',
        section: 'Hábitos de Vida',
        options: [
          '1 - Muito baixo',
          '5 - Moderado',
          '10 - Muito alto',
        ],
        is_required: true,
        order_index: 5,
      },
      {
        question_text: 'Pratica atividade física? Com que frequência?',
        question_type: 'single_choice',
        section: 'Hábitos de Vida',
        options: [
          'Não pratico',
          '1-2 vezes por semana',
          '3-4 vezes por semana',
          '5 ou mais vezes por semana',
        ],
        is_required: true,
        order_index: 6,
      },
      {
        question_text: 'Consome bebidas alcoólicas?',
        question_type: 'single_choice',
        section: 'Hábitos de Vida',
        options: [
          'Não consumo',
          'Eventualmente',
          'Fins de semana',
          'Diariamente',
        ],
        is_required: true,
        order_index: 7,
      },
      {
        question_text: 'Fuma ou já fumou?',
        question_type: 'single_choice',
        section: 'Hábitos de Vida',
        options: [
          'Nunca fumei',
          'Ex-fumante',
          'Sim, fumo atualmente',
        ],
        is_required: true,
        order_index: 8,
      },
      {
        question_text: 'Quantos litros de água você consome por dia?',
        question_type: 'single_choice',
        section: 'Hábitos de Vida',
        options: [
          'Menos de 1L',
          '1-2L',
          '2-3L',
          'Mais de 3L',
        ],
        is_required: true,
        order_index: 9,
      },

      // Patologias
      {
        question_text: 'Possui alguma doença diagnosticada?',
        question_type: 'multiple_choice',
        section: 'Patologias',
        options: [
          'Diabetes',
          'Hipertensão',
          'Colesterol alto',
          'Problemas de tireoide',
          'Gastrite/Refluxo',
          'Problemas intestinais',
          'Alergias alimentares',
          'Outro',
          'Nenhuma',
        ],
        is_required: true,
        order_index: 10,
      },
      {
        question_text: 'Histórico familiar de doenças',
        question_type: 'text',
        section: 'Patologias',
        is_required: false,
        order_index: 11,
      },
      {
        question_text: 'Faz uso de medicamentos? Quais?',
        question_type: 'text',
        section: 'Patologias',
        is_required: false,
        order_index: 12,
      },
      {
        question_text: 'Faz uso de suplementos? Quais?',
        question_type: 'text',
        section: 'Patologias',
        is_required: false,
        order_index: 13,
      },

      // Avaliação Clínica
      {
        question_text: 'Peso atual (kg)',
        question_type: 'number',
        section: 'Avaliação Clínica',
        is_required: true,
        order_index: 14,
      },
      {
        question_text: 'Altura (cm)',
        question_type: 'number',
        section: 'Avaliação Clínica',
        is_required: true,
        order_index: 15,
      },
      {
        question_text: 'Peso desejado (kg)',
        question_type: 'number',
        section: 'Avaliação Clínica',
        is_required: false,
        order_index: 16,
      },
      {
        question_text: 'Circunferência da cintura (cm)',
        question_type: 'number',
        section: 'Avaliação Clínica',
        is_required: false,
        order_index: 17,
      },
      {
        question_text: 'Circunferência do quadril (cm)',
        question_type: 'number',
        section: 'Avaliação Clínica',
        is_required: false,
        order_index: 18,
      },
      {
        question_text: 'Possui exames recentes? Descreva os principais resultados',
        question_type: 'text',
        section: 'Avaliação Clínica',
        is_required: false,
        order_index: 19,
      },

      // Sintomas e Rastreamento Metabólico
      {
        question_text: 'Apresenta algum destes sintomas?',
        question_type: 'multiple_choice',
        section: 'Sintomas',
        options: [
          'Fadiga/Cansaço constante',
          'Problemas intestinais',
          'Gases/Inchaço abdominal',
          'Dores de cabeça frequentes',
          'Insônia',
          'Ansiedade',
          'Compulsão alimentar',
          'Queda de cabelo',
          'Unhas fracas',
          'Pele seca',
          'Nenhum',
        ],
        is_required: true,
        order_index: 20,
      },
      {
        question_text: 'Como está seu funcionamento intestinal?',
        question_type: 'single_choice',
        section: 'Sintomas',
        options: [
          'Normal (1x ao dia)',
          'Constipação',
          'Diarreia',
          'Alternado',
        ],
        is_required: true,
        order_index: 21,
      },
      {
        question_text: 'Possui desconfortos digestivos após as refeições?',
        question_type: 'text',
        section: 'Sintomas',
        is_required: false,
        order_index: 22,
      },

      // Hábitos Alimentares
      {
        question_text: 'Quantas refeições você faz por dia?',
        question_type: 'single_choice',
        section: 'Hábitos Alimentares',
        options: [
          '1-2 refeições',
          '3 refeições',
          '4-5 refeições',
          'Mais de 5 refeições',
        ],
        is_required: true,
        order_index: 23,
      },
      {
        question_text: 'Onde você faz a maioria das refeições?',
        question_type: 'single_choice',
        section: 'Hábitos Alimentares',
        options: [
          'Em casa',
          'No trabalho',
          'Em restaurantes',
          'Misto',
        ],
        is_required: true,
        order_index: 24,
      },
      {
        question_text: 'Quem prepara suas refeições?',
        question_type: 'single_choice',
        section: 'Hábitos Alimentares',
        options: [
          'Eu mesmo',
          'Família',
          'Restaurante/Delivery',
          'Misto',
        ],
        is_required: true,
        order_index: 25,
      },
      {
        question_text: 'Com que frequência consome fast food?',
        question_type: 'single_choice',
        section: 'Hábitos Alimentares',
        options: [
          'Nunca',
          'Raramente',
          '1-2 vezes por semana',
          '3 ou mais vezes por semana',
        ],
        is_required: true,
        order_index: 26,
      },
      {
        question_text: 'Possui restrições ou preferências alimentares?',
        question_type: 'multiple_choice',
        section: 'Hábitos Alimentares',
        options: [
          'Vegetariano',
          'Vegano',
          'Sem lactose',
          'Sem glúten',
          'Low carb',
          'Nenhuma',
        ],
        is_required: true,
        order_index: 27,
      },
      {
        question_text: 'Liste os alimentos que você NÃO gosta ou NÃO consome',
        question_type: 'text',
        section: 'Hábitos Alimentares',
        is_required: false,
        order_index: 28,
      },
      {
        question_text: 'Tem alguma alergia ou intolerância alimentar?',
        question_type: 'text',
        section: 'Hábitos Alimentares',
        is_required: false,
        order_index: 29,
      },
      {
        question_text: 'Descreva seu café da manhã típico',
        question_type: 'text',
        section: 'Hábitos Alimentares',
        is_required: false,
        order_index: 30,
      },
      {
        question_text: 'Descreva seu almoço típico',
        question_type: 'text',
        section: 'Hábitos Alimentares',
        is_required: false,
        order_index: 31,
      },
      {
        question_text: 'Descreva seu jantar típico',
        question_type: 'text',
        section: 'Hábitos Alimentares',
        is_required: false,
        order_index: 32,
      },

      // Informações Adicionais
      {
        question_text: 'Observações adicionais ou informações que considere relevantes',
        question_type: 'text',
        section: 'Informações Adicionais',
        is_required: false,
        order_index: 33,
      },
    ],
  },
  {
    id: 'recordatorio-simples',
    name: 'Recordatório Alimentar 24h',
    category: 'recordatorio',
    description: 'Questionário para registro do consumo alimentar das últimas 24 horas',
    estimatedTime: 10,
    questions: [
      {
        question_text: 'Café da Manhã - O que você comeu?',
        question_type: 'text',
        section: 'Refeições',
        is_required: true,
        order_index: 0,
      },
      {
        question_text: 'Café da Manhã - Que horas foi?',
        question_type: 'text',
        section: 'Refeições',
        is_required: false,
        order_index: 1,
      },
      {
        question_text: 'Lanche da Manhã - O que você comeu?',
        question_type: 'text',
        section: 'Refeições',
        is_required: false,
        order_index: 2,
      },
      {
        question_text: 'Almoço - O que você comeu?',
        question_type: 'text',
        section: 'Refeições',
        is_required: true,
        order_index: 3,
      },
      {
        question_text: 'Almoço - Que horas foi?',
        question_type: 'text',
        section: 'Refeições',
        is_required: false,
        order_index: 4,
      },
      {
        question_text: 'Lanche da Tarde - O que você comeu?',
        question_type: 'text',
        section: 'Refeições',
        is_required: false,
        order_index: 5,
      },
      {
        question_text: 'Jantar - O que você comeu?',
        question_type: 'text',
        section: 'Refeições',
        is_required: true,
        order_index: 6,
      },
      {
        question_text: 'Jantar - Que horas foi?',
        question_type: 'text',
        section: 'Refeições',
        is_required: false,
        order_index: 7,
      },
      {
        question_text: 'Ceia ou Lanche Noturno - O que você comeu?',
        question_type: 'text',
        section: 'Refeições',
        is_required: false,
        order_index: 8,
      },
      {
        question_text: 'Consumiu água? Quantos copos aproximadamente?',
        question_type: 'text',
        section: 'Hidratação',
        is_required: false,
        order_index: 9,
      },
    ],
  },
  {
    id: 'satisfacao-semanal',
    name: 'Feedback de Satisfação Semanal',
    category: 'satisfacao',
    description: 'Questionário para avaliar a satisfação do paciente com o plano alimentar',
    estimatedTime: 5,
    questions: [
      {
        question_text: 'Como você avalia sua semana de alimentação?',
        question_type: 'scale',
        section: 'Avaliação Geral',
        options: [
          '1 - Muito ruim',
          '5 - Regular',
          '10 - Excelente',
        ],
        is_required: true,
        order_index: 0,
      },
      {
        question_text: 'Conseguiu seguir o plano alimentar?',
        question_type: 'single_choice',
        section: 'Adesão',
        options: [
          'Sim, totalmente',
          'Parcialmente',
          'Pouco',
          'Não consegui',
        ],
        is_required: true,
        order_index: 1,
      },
      {
        question_text: 'Quais foram as principais dificuldades?',
        question_type: 'multiple_choice',
        section: 'Dificuldades',
        options: [
          'Falta de tempo',
          'Dificuldade no preparo',
          'Ingredientes indisponíveis',
          'Senti muita fome',
          'Rotina familiar',
          'Rotina de trabalho',
          'Nenhuma',
        ],
        is_required: false,
        order_index: 2,
      },
      {
        question_text: 'Como está se sentindo fisicamente?',
        question_type: 'multiple_choice',
        section: 'Resultados',
        options: [
          'Mais energia',
          'Menos inchaço',
          'Dormindo melhor',
          'Menos fome',
          'Sem mudanças',
        ],
        is_required: true,
        order_index: 3,
      },
      {
        question_text: 'Gostaria de fazer alguma alteração no plano?',
        question_type: 'text',
        section: 'Sugestões',
        is_required: false,
        order_index: 4,
      },
      {
        question_text: 'Observações adicionais',
        question_type: 'text',
        section: 'Sugestões',
        is_required: false,
        order_index: 5,
      },
    ],
  },
];

export function getTemplateById(id: string): QuestionnaireTemplate | undefined {
  return QUESTIONNAIRE_TEMPLATES.find(t => t.id === id);
}
