export const mockSalaoUser = {
  id: '1',
  name: 'Bella Beauty Salon',
  email: 'contato@bellabeauty.com',
  plan: 'Pro',
  createdAt: '2024-01-15',
};

export const mockSalaoData = {
  businessName: 'Bella Beauty Salon',
  ownerName: 'Isabella Santos',
  cnpj: '23.456.789/0001-12',
  address: 'Rua da Beleza, 456 - Centro',
  phone: '(11) 3789-0123',
  whatsapp: '(11) 94789-0123',
};

export const mockSalaoAnalytics = {
  totalAppointments: 892,
  totalRevenue: 45600,
  totalClients: 342,
  aiInteractions: 678,
  conversionRate: 24.5,
  avgTicket: 95.50,
  
  monthlyData: [
    { month: 'Jan', appointments: 78, revenue: 8900, clients: 65 },
    { month: 'Fev', revenue: 9200, appointments: 82, clients: 68 },
    { month: 'Mar', revenue: 10100, appointments: 89, clients: 72 },
    { month: 'Abr', revenue: 8800, appointments: 76, clients: 63 },
    { month: 'Mai', revenue: 11500, appointments: 95, clients: 78 },
  ],
  
  topServices: [
    { name: 'Corte Feminino', bookings: 234, revenue: 11700 },
    { name: 'Coloração', bookings: 167, revenue: 15030 },
    { name: 'Escova/Prancha', bookings: 198, revenue: 7920 },
    { name: 'Manicure', bookings: 189, revenue: 5670 },
    { name: 'Design de Sobrancelhas', bookings: 145, revenue: 4350 },
  ],
};

export const mockServices = [
  {
    id: '1',
    name: 'Corte Feminino',
    category: 'Cabelo',
    duration: 60,
    price: 50.00,
    professional: 'Isabella Santos',
    description: 'Corte personalizado para todos os tipos de cabelo',
    available: true,
  },
  {
    id: '2',
    name: 'Coloração Completa',
    category: 'Cabelo',
    duration: 180,
    price: 120.00,
    professional: 'Maria Silva',
    description: 'Coloração com produtos profissionais',
    available: true,
  },
  {
    id: '3',
    name: 'Escova Progressiva',
    category: 'Cabelo',
    duration: 240,
    price: 200.00,
    professional: 'Isabella Santos',
    description: 'Alisamento com produtos de alta qualidade',
    available: true,
  },
  {
    id: '4',
    name: 'Manicure Tradicional',
    category: 'Unhas',
    duration: 45,
    price: 25.00,
    professional: 'Ana Costa',
    description: 'Cuidados completos para as unhas das mãos',
    available: true,
  },
  {
    id: '5',
    name: 'Pedicure Spa',
    category: 'Unhas',
    duration: 60,
    price: 35.00,
    professional: 'Ana Costa',
    description: 'Relaxamento e cuidados para os pés',
    available: true,
  },
  {
    id: '6',
    name: 'Design de Sobrancelhas',
    category: 'Sobrancelhas',
    duration: 30,
    price: 30.00,
    professional: 'Carla Mendes',
    description: 'Modelagem e design personalizado',
    available: true,
  },
];

export const mockProfessionals = [
  {
    id: '1',
    name: 'Isabella Santos',
    specialty: 'Cabeleireira',
    services: ['Corte Feminino', 'Escova Progressiva', 'Penteados'],
    workingDays: ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    workingHours: '09:00 - 18:00',
    commissionRate: 60,
    totalBookings: 234,
    rating: 4.9,
  },
  {
    id: '2',
    name: 'Maria Silva',
    specialty: 'Colorista',
    services: ['Coloração', 'Mechas', 'Luzes'],
    workingDays: ['Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    workingHours: '09:00 - 17:00',
    commissionRate: 55,
    totalBookings: 189,
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Ana Costa',
    specialty: 'Manicure/Pedicure',
    services: ['Manicure', 'Pedicure', 'Nail Art'],
    workingDays: ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    workingHours: '08:00 - 17:00',
    commissionRate: 50,
    totalBookings: 298,
    rating: 4.7,
  },
];

export const mockAppointments = [
  {
    id: 'AG-001',
    client: 'Amanda Oliveira',
    clientPhone: '(11) 98765-4321',
    service: 'Corte Feminino',
    professional: 'Isabella Santos',
    date: '2024-01-22',
    time: '10:00',
    duration: 60,
    price: 50.00,
    status: 'Agendado',
    paymentMethod: 'Cartão',
    notes: 'Cliente quer manter o comprimento',
  },
  {
    id: 'AG-002',
    client: 'Carla Santos',
    clientPhone: '(11) 94567-8901',
    service: 'Coloração Completa',
    professional: 'Maria Silva',
    date: '2024-01-22',
    time: '14:00',
    duration: 180,
    price: 120.00,
    status: 'Em Andamento',
    paymentMethod: 'PIX',
    notes: 'Primeira coloração, teste de alergia feito',
  },
  {
    id: 'AG-003',
    client: 'Beatriz Lima',
    clientPhone: '(11) 93456-7890',
    service: 'Manicure + Pedicure',
    professional: 'Ana Costa',
    date: '2024-01-22',
    time: '09:30',
    duration: 90,
    price: 60.00,
    status: 'Concluído',
    paymentMethod: 'Dinheiro',
    notes: 'Esmalte vermelho',
  },
];

export const mockClients = [
  {
    id: '1',
    name: 'Amanda Oliveira',
    phone: '(11) 98765-4321',
    email: 'amanda.oliveira@email.com',
    birthDate: '1990-05-15',
    address: 'Rua das Flores, 123 - São Paulo/SP',
    firstVisit: '2023-03-15',
    lastVisit: '2024-01-18',
    totalVisits: 12,
    totalSpent: 650.00,
    preferredProfessional: 'Isabella Santos',
    favoriteServices: ['Corte Feminino', 'Escova'],
    notes: 'Alérgica a produtos com amônia',
    status: 'Ativo',
  },
  {
    id: '2',
    name: 'Carla Santos',
    phone: '(11) 94567-8901',
    email: 'carla.santos@email.com',
    birthDate: '1985-08-22',
    address: 'Av. Paulista, 1000 - São Paulo/SP',
    firstVisit: '2023-11-20',
    lastVisit: '2024-01-20',
    totalVisits: 6,
    totalSpent: 420.00,
    preferredProfessional: 'Maria Silva',
    favoriteServices: ['Coloração', 'Corte'],
    notes: 'Cabelo muito sensível, usar produtos suaves',
    status: 'Ativo',
  },
  {
    id: '3',
    name: 'Beatriz Lima',
    phone: '(11) 93456-7890',
    email: 'beatriz.lima@email.com',
    birthDate: '1992-12-03',
    address: 'Rua do Comércio, 456 - São Paulo/SP',
    firstVisit: '2022-08-10',
    lastVisit: '2024-01-22',
    totalVisits: 24,
    totalSpent: 1200.00,
    preferredProfessional: 'Ana Costa',
    favoriteServices: ['Manicure', 'Pedicure', 'Design Sobrancelha'],
    notes: 'Cliente VIP, sempre pontual',
    status: 'Ativo',
  },
];

export const mockChatMessages = [
  {
    id: '1',
    sender: 'customer',
    customer: 'Amanda Oliveira',
    message: 'Oi! Gostaria de agendar um corte para amanhã',
    timestamp: '2024-01-21 14:30',
    status: 'read',
  },
  {
    id: '2',
    sender: 'ai',
    message: 'Olá Amanda! Claro, posso te ajudar com o agendamento. Que horário você prefere? Temos disponibilidade às 10h, 14h e 16h com a Isabella.',
    timestamp: '2024-01-21 14:31',
    status: 'sent',
  },
  {
    id: '3',
    sender: 'customer',
    customer: 'Amanda Oliveira',
    message: 'Às 10h seria perfeito!',
    timestamp: '2024-01-21 14:32',
    status: 'read',
  },
  {
    id: '4',
    sender: 'ai',
    message: 'Perfeito! Agendei seu corte para amanhã às 10h com a Isabella. O valor é R$ 50,00. Precisa de mais alguma coisa?',
    timestamp: '2024-01-21 14:33',
    status: 'sent',
  },
  {
    id: '5',
    sender: 'user',
    message: 'Cliente confirmou o agendamento. Enviando lembrete por WhatsApp.',
    timestamp: '2024-01-21 15:45',
    status: 'sent',
  },
];