// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmjzalbrehakxhvwrdkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtanphbGJyZWhha3hodndyZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDgzNTYsImV4cCI6MjA3NDU4NDM1Nn0.QVru71BO_pMkblcFb6uQ_68kRCXfmfiGQV2Rv5_iKsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});